ARG BASE_IMAGE=nvcr.io/nvidia/tensorflow:20.08-tf2-py3

FROM $BASE_IMAGE

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -yq --no-install-recommends htop rsync;

CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
